"""empty message

Revision ID: 010c75783fd6
Revises: b68fa9a68d6c
Create Date: 2017-11-23 17:35:07.352382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '010c75783fd6'
down_revision = 'b68fa9a68d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fooddistributioncenters', 'opening_time')
    op.drop_column('fooddistributioncenters', 'closing_time')
    op.drop_column('fooddistributioncenters', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fooddistributioncenters', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('fooddistributioncenters', sa.Column('closing_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('fooddistributioncenters', sa.Column('opening_time', postgresql.TIME(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
