"""empty message

Revision ID: 0854600f49a3
Revises: 010c75783fd6
Create Date: 2017-11-23 17:35:53.975575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0854600f49a3'
down_revision = '010c75783fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fooddistributioncenters', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('fooddistributioncenters', sa.Column('closing_time', sa.Time(), nullable=True))
    op.add_column('fooddistributioncenters', sa.Column('opening_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fooddistributioncenters', 'opening_time')
    op.drop_column('fooddistributioncenters', 'closing_time')
    op.drop_column('fooddistributioncenters', 'address')
    # ### end Alembic commands ###
