"""empty message

Revision ID: 2104250544ef
Revises: 975ab15794f4
Create Date: 2017-12-04 11:39:25.698324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2104250544ef'
down_revision = '975ab15794f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
