"""empty message

Revision ID: 8e6369d11a36
Revises: 3202d51ddc9e
Create Date: 2017-11-28 17:48:32.861602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6369d11a36'
down_revision = '3202d51ddc9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column('fooddistributioncenters', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fooddistributioncenters', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fooddistributioncenters', type_='foreignkey')
    op.drop_column('fooddistributioncenters', 'admin_id')
    op.drop_table('users')
    # ### end Alembic commands ###
