"""empty message

Revision ID: d2623162c574
Revises: 2104250544ef
Create Date: 2017-12-05 00:32:59.250607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2623162c574'
down_revision = '2104250544ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickups', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pickups', 'description')
    # ### end Alembic commands ###
